### ISSUE TITLE
text on extra cmdbar is unreadable

### ISSUE THREAD

**Issue by opakholis** [catppuccin/gitui#1]
The background in the extra cmdbar is too conspicuous, which causes the text to be unreadable. The following screenshot illustrates the issue with palette "Mocha" and occurs in other palettes as well

![image](https://user-images.githubusercontent.com/49778014/199926806-bf0808ec-6db2-48ca-9d95-015af243de1f.png)

**Comment by BlueFalconHD** [comment]
This might be an issue with Gitui itself. I'll look into it.
