### ISSUE TITLE
Update README for newer versions of gitui

### ISSUE THREAD

**Issue by ghost** [catppuccin/gitui#3]
Thanks for the themes! The default one is atrocious..

Be that as it may, it appears that `gitui` now supports changing the default theme by editing `~/.config/gitui/theme.ron`. I didn't see the changes until I restarted `gitui`.

**Comment by Koba-gh** [comment]
Yeah! I ran the commands below and it worked fine without alias and editing my rc file.
```
git clone https://github.com/catppuccin/gitui
cd gitui/theme
cp mocha.ron ~/.config/gitui/theme.ron
```

**Comment by sgoudham** [comment]
Closed in https://github.com/catppuccin/gitui/commit/05ba5fb1430b9ede001d88102f167cd6cb09f26b, thanks for raising!
